config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.confirmed? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :cancel_vote
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: %i[create]
  end

  use_doorkeeper

  root to: 'questions#index'

  get 'search', to: 'search#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  post 'users/confirm_email', to: 'users#confirm_email'

  resources :questions do
    concerns :votable, :commentable

    member do
      delete :destroy_file
      delete :destroy_link
    end

    resources :answers, shallow: true, only: %i[create update destroy] do
      concerns :votable, :commentable

      member do
        post :best
        delete :destroy_file
        delete :destroy_link
      end
    end

    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resource :achievements, only: %i[show]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit]
      end
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  belongs_to :user
  belongs_to :best_answer, class_name: 'Answer', optional: true

  has_one :reward, dependent: :destroy

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many_attached :files

  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :subscribe_author

  def mark_as_best(answer)
    update(best_answer: answer)
  end

  def subscribed_by?(user)
    subscriptions.find_by(user:)
  end

  private

  def subscribe_author
    subscriptions.create(user:)
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

class Api::V1::QuestionsController < Api::V1::BaseController
  def index
    questions = Question.all

    render json: questions
  end

  def show
    render json: question
  end

  def create
    question = current_resource_owner.questions.build(question_params)

    if question.save
      render json: question, status: :created
    else
      render json: { errors: question.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize question

    if question.update(question_params)
      render json: question, status: :created
    else
      render json: { errors: question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize question

    if question.destroy
      render json: question, status: :ok
    else
      render json: { errors: 'An error occurred while destroying Question' }, status: :unprocessable_entity
    end
  end

  private

  def question_params
    params.require(:question).permit(
      :title,
      :body,
      links_attributes: %i[id title url],
      reward_attributes: %i[title image_url]
    )
  end

  def question
    @question ||= Question.find(params[:id])
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_question, except: %i[index new create]

  def index
    @questions = Question.all
  end

  def new
    @question = current_user.questions.build
    @question.links.build
    @question.build_reward
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      flash[:success] = 'Your Question successfully created!'
      publish_question

      redirect_to @question
    else
      render :new
    end
  end

  # rubocop:disable Metrics/AbcSize
  def show
    @user_vote = @question.votes.find_by(user: current_user)
    @subscription = @question.subscriptions.find_by(user: current_user)
    @best_answer = @question.best_answer
    @answers = @question.answers.with_attached_files.where.not(id: @best_answer&.id)
    @answer = @question.answers.build
    @answer.links.build
    @question_comment = @question.comments.build
    @answer_comment = @answer.comments.build
  end
  # rubocop:enable Metrics/AbcSize

  def update
    authorize @question

    @question.update(question_params)
  end

  def destroy
    authorize @question

    @question.destroy
    flash[:success] = 'Your Question successfully deleted!'

    redirect_to questions_path
  end

  def destroy_file
    authorize @question

    @file = ActiveStorage::Attachment.find(params[:file_id])
    @file.purge
  end

  def destroy_link
    authorize @question

    @link = Link.find(params[:link_id])
    @link.destroy
  end

  private

  def publish_question
    html = ApplicationController.render(
      partial: 'questions/question',
      locals: { question: @question }
    )

    ActionCable.server.broadcast('questions', html)
  end

  def question_params
    params.require(:question).permit(
      :title,
      :body,
      files: [],
      links_attributes: %i[id title url],
      reward_attributes: %i[title image_url]
    )
  end

  def set_question
    @question = Question.with_attached_files.find(params[:id])
  end
end

app/views/questions/_edit_form.html.slim
= form_with(model: @question, local: false) do |f|
  .question-errors
    = render 'shared/errors', object: f.object

  .mb-3
    = f.text_field :title, class: 'form-control'

  .mb-3
    = f.text_area :body, class: 'form-control'

  .mb-3
    = f.file_field :files, multiple: true, direct_upload: true, class: 'form-control'

  .mb-3
    #question-links
      = f.fields_for :links do |link_f|
        = render 'link_fields', f: link_f

      .links
        = link_to_add_association 'Add link', f, :links

  = f.submit 'Save', class: 'btn btn-sm btn-info'

app/views/questions/_file.html.slim
div id="question-file-#{file.id}" class="small"
  => link_to file.filename.to_s, url_for(file), class: 'text-decoration-none'

  - if policy(@question).destroy_file?
    span class="badge bg-danger rounded-pill"
      = link_to '',
                destroy_file_question_path(file_id: file.id),
                method: :delete, remote: true,
                class: 'btn-close btn-close-white'

app/views/questions/_link.html.slim
div id="question-link-#{link.id}" class="small"
  => link_to link.title,
             link.url,
             class: "text-decoration-none #{'gist-link' if link.gist?}",
             data: { link_id: link.id }

  - if policy(@question).destroy_link?
    span class="badge bg-danger rounded-pill"
      = link_to '',
                destroy_link_question_path(link_id: link.id),
                method: :delete, remote: true,
                class: 'btn-close btn-close-white'

  - if link.gist?
    div class="gist-content border border-light bg-light rounded-3 my-2 p-2 hidden"

app/views/questions/_new_answer.html.slim
div class="card mt-5 mb-3"
  .card-header
    h3 Your Answer

  .card-body
    = form_with(model: [@question, answer], class: 'new-answer-form', local: false) do |f|
      .new-answer-errors
        = render 'shared/errors', object: f.object

      .mb-3
        = f.label :body, 'Text', class: 'form-label'
        = f.text_area :body, size: 'x8', class: 'form-control'

      .mb-3
        = f.label :files, class: 'form-label'
        = f.file_field :files, multiple: true, direct_upload: true, class: 'form-control'

      .mb-3
        label.form-label Links

        #answer-links
          = f.fields_for :links do |link_f|
            = render 'answers/link_fields', f: link_f
          .links
            = link_to_add_association 'Add link', f, :links

      = f.submit 'Post Your Answer', class: 'btn btn-sm btn-info'

app/views/questions/_question.html.slim
div class="card mt-3"
  div.card-header
    = link_to question.title, question, class: 'text-decoration-none'

  div.card-body
    div.card-text
      ' by
      span.text-info
        => question.user.email
      = "#{time_ago_in_words(question.created_at)} ago"

app/views/questions/_subscribe.html.slim
div class="subscription-control mt-3"
  = button_to 'Subscribe',
    question_subscriptions_path(@question),
    remote: true,
    class: "btn btn-info subscribe-button #{'hidden' if @question.subscribed_by?(current_user)}"

  - if @question.subscribed_by?(current_user)
    = button_to 'Unsubscribe',
      subscription_path(@subscription),
      method: :delete,
      remote: true,
      class: "btn btn-secondary unsubscribe-button"

app/views/questions/_vote.html.slim
div class="vote-control d-flex align-items-center"
  = button_to vote_up_question_path(@question),
              form: { data: { type: :json }, class: 'vote-up-form' },
              remote: true,
              class: "vote-up btn border-0 #{'hidden' if @user_vote&.rate&.positive?}"
    = image_tag('vote-up.png')

  = button_to cancel_vote_question_path(@question),
              form: { data: { type: :json },
                      class: "vote-up-cancel-form #{'hidden' unless @user_vote&.rate&.positive?}" },
              method: :delete,
              remote: true,
              class: "vote-up-cancel btn border-0 #{'upvoted' if @user_vote&.rate&.positive?}"
    = image_tag('vote-up.png')

  span class="fs-1 rating"
    = @question.rating

  = button_to vote_down_question_path(@question),
              form: { data: { type: :json }, class: 'vote-down-form' },
              remote: true,
              class: "vote-down btn border-0 #{'hidden' if @user_vote&.rate&.negative?}"
    = image_tag('vote-down.png')

  = button_to cancel_vote_question_path(@question),
              form: { data: { type: :json },
                      class: "vote-down-cancel-form #{'hidden' unless @user_vote&.rate&.negative?}" },
              method: :delete,
              remote: true,
              class: "vote-down-cancel btn border-0 #{'downvoted' if @user_vote&.rate&.negative?}"
    = image_tag('vote-down.png')

app/views/questions/destroy_file.js.erb
$('#question-file-' + <%= @file.id %>).remove()

<% @question.reload %>

<% unless @question.files.attached? %>
  $('.question-files-card').addClass('hidden')
<% end %>

app/views/questions/destroy_link.js.erb
$('#question-link-' + <%= @link.id %>).remove()

<% if @question.links.empty? %>
  $('.question-links-card').addClass('hidden')
<% end %>

$('.edit-question-form').html('<%= j render 'edit_form' %>')

app/views/questions/index.html.slim
= link_to 'Ask Question', new_question_path, class: 'btn btn-primary btn-lg'

div class="questions mt-3"
  = render @questions

app/views/questions/new.html.slim
h1.mb-3
  | New Question

div
  = form_with(model: @question, local: true) do |f|
    = render 'shared/errors', object: f.object

    .mb-3
      = f.label :title, class: 'form-label'
      = f.text_field :title, class: 'form-control'

    .mb-3
      = f.label :body, 'Text', class: 'form-label'
      = f.text_area :body, class: 'form-control'

    .mb-3
      = f.label :files, class: 'form-label'
      = f.file_field :files, multiple: true, direct_upload: true, class: 'form-control'

    .mb-3
      label.form-label Links

      #question-links
        = f.fields_for :links do |link_f|
          = render 'link_fields', f: link_f
        .links
          = link_to_add_association 'Add link', f, :links

    .mb-3
      label.form-label Reward

      div id="question-reward" class="row"
        = f.fields_for :reward do |reward_f|
          div.col
            = reward_f.text_field :title, placeholder: 'title', class: 'form-control form-control-sm'

          div.col
            = reward_f.text_field :image_url, placeholder: 'image url', class: 'form-control form-control-sm'

    = f.submit 'Create', class: 'btn btn-primary'

app/views/questions/show.html.slim
div id="question-#{@question.id}" data-question-id="#{@question.id}"
  .question
    div class="row row-cols-lg-2"
      - if current_user
        div class="col-lg-2 d-flex justify-content-center"
          = render 'vote'

      div class="col-lg-10"
        h1.question-title
          => @question.title

        - if policy(@question).update?
          .question-control
            => link_to 'Edit', '#', class: 'edit-question-link btn btn-sm btn-warning'

            - if policy(@question).destroy?
              = link_to 'Delete',
                        question_path(@question),
                        method: :delete, data: { turbo: false, confirm: 'Are you sure?' },
                        class: 'btn btn-sm btn-danger'

        div class="hidden edit-question-form mt-3"
          = render 'edit_form'

        div class="mt-3 small text-muted"
          => "Asked #{time_ago_in_words(@question.created_at)} ago by"
          span.text-info
            = @question.user.email

          div
            - if @question.reward
              | Author offers a Reward for Best Answer!

        - if current_user
          = render 'subscribe'

    hr

    div class="question-body mb-3"
      = @question.body

    hr

    div.comments
      = render @question.comments

    - if current_user
      = render 'comments/form', commentable: @question, comment: @question_comment

    .row
      div class="col mb-3 question-files-card #{'hidden' unless @question.files.attached?}"
        .card
          .card-header
            label.small Files

          div class="question-files card-body"
            = render partial: 'file', collection: @question.files

      div class="col question-links-card #{'hidden' if @question.links.empty?}"
        .card
          .card-header
            label.small Links

          div class="question-links card-body"
            = render partial: 'link', collection: @question.links

h3.mt-3 Answers

div class="answers ms-lg-5 mt-3"
  - if @best_answer
    = render @best_answer
  = render @answers

- if user_signed_in?
  .new-answer
    = render 'new_answer', answer: @answer

div class="toast-container position-fixed bottom-0 end-0 p-3"
  div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="2000"
    div class="toast-body bg-warning"

app/views/questions/unsubscribe.js.erb
$('.unsubscribe-button').addClass('hidden')
$('.subscribe-button').removeClass('hidden')

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', object: @question %>')

<% if @question.errors.empty? %>
  $('.question-title').html('<%= @question.title %>')
  $('.question-body').html('<%= @question.body %>')

  <% if @question.files.attached? %>
    $('.question-files-card').removeClass('hidden')
    $('.question-files').html('<%= j render partial: 'file', collection: @question.files %>')
  <% end %>

  <% if @question.links.any? %>
    $('.question-links-card').removeClass('hidden')
    $('.question-links').html('<%= j render partial: 'link', collection: @question.links %>')
  <% end %>

  $('.edit-question-form').html('<%= j render 'edit_form' %>').addClass('hidden')
  $('.edit-question-link').show()
<% end %>