config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.confirmed? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :cancel_vote
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: %i[create]
  end

  use_doorkeeper

  root to: 'questions#index'

  get 'search', to: 'search#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  post 'users/confirm_email', to: 'users#confirm_email'

  resources :questions do
    concerns :votable, :commentable

    member do
      delete :destroy_file
      delete :destroy_link
    end

    resources :answers, shallow: true, only: %i[create update destroy] do
      concerns :votable, :commentable

      member do
        post :best
        delete :destroy_file
        delete :destroy_link
      end
    end

    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resource :achievements, only: %i[show]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit]
      end
    end
  end
end

app/views/shared/_errors.html.slim
- if object.present? && object.errors.any?
  div class="alert alert-danger"
    ul.mb-0
      - object.errors.full_messages.each do |message|
        li= message

app/views/shared/_menu.html.slim
header class="navbar navbar-expand-lg navbar-light"
  .container
    = link_to 'QnA', root_path, class: 'navbar-brand'

    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon

    div class="collapse navbar-collapse justify-content-between" id="navbarNav"
      ul.navbar-nav
        li.nav-item
          = link_to 'Questions', questions_path, class: 'nav-link'

      nav
        ul class="nav navbar-nav col-12 col-lg-auto mb-md-0"
          - if user_signed_in?
            li.dropdown
              = link_to current_user.email, '#', class: 'dropdown-toggle nav-link', data: { 'bs-toggle' => 'dropdown' }
              ul.dropdown-menu
                li
                  = link_to 'Achievements', achievements_path, class: 'nav-link'
                li
                  = link_to 'Log out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'nav-link'
          - else
            li= link_to 'Log in', new_user_session_path, class: 'nav-link'
            li= link_to 'Sign up', new_user_registration_path, class: 'nav-link'