config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.confirmed? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :cancel_vote
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: %i[create]
  end

  use_doorkeeper

  root to: 'questions#index'

  get 'search', to: 'search#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  post 'users/confirm_email', to: 'users#confirm_email'

  resources :questions do
    concerns :votable, :commentable

    member do
      delete :destroy_file
      delete :destroy_link
    end

    resources :answers, shallow: true, only: %i[create update destroy] do
      concerns :votable, :commentable

      member do
        post :best
        delete :destroy_file
        delete :destroy_link
      end
    end

    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resource :achievements, only: %i[show]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit]
      end
    end
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  belongs_to :user
  belongs_to :question, touch: true

  has_many_attached :files

  validates :body, presence: true

  after_create :notify_question_subscribers

  private

  def notify_question_subscribers
    QuestionNotificationJob.perform_later(question)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :set_answer, only: %i[update destroy best destroy_file destroy_link]
  before_action :set_question, only: %i[update destroy best]

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params.merge(user: current_user))

    publish_answer if @answer.save

    @answer_comment = @answer.comments.build
    @new_answer = @question.answers.build
    @new_answer.links.build
  end

  def update
    authorize @answer

    @best_answer = @question.best_answer

    @answer.update(answer_params)
    @answer_comment = @answer.comments.build
  end

  def destroy
    authorize @answer

    @answer.destroy
  end

  def best
    authorize @answer

    @question.mark_as_best(@answer)
    @question.reward&.update(user: @answer.user)
  end

  def destroy_file
    authorize @answer

    @file = ActiveStorage::Attachment.find(params[:file_id])
    @file.purge
  end

  def destroy_link
    authorize @answer

    @link = Link.find(params[:link_id])
    @link.destroy
  end

  private

  def publish_answer
    html = ApplicationController.render(
      partial: 'answers/answer_simplified',
      locals: { answer: @answer }
    )

    ActionCable.server.broadcast(
      "question_#{@question.id}",
      { html:, author_id: @answer.user.id }
    )
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[id title url])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = @answer.question
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

class Api::V1::AnswersController < Api::V1::BaseController
  def index
    render json: question.answers
  end

  def show
    answer = question.answers.find(params[:id])

    render json: answer
  end

  def create
    answer = question.answers.build(answer_params.merge(user: current_resource_owner))

    if answer.save
      render json: answer, status: :created
    else
      render json: { errors: answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize answer

    if answer.update(answer_params)
      render json: answer, status: :created
    else
      render json: { errors: answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize answer

    if answer.destroy
      render json: answer, status: :ok
    else
      render json: { errors: 'An error occurred while destroying Answer' }, status: :unprocessable_entity
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body, links_attributes: %i[id title url])
  end

  def question
    @question ||= Question.find(params[:question_id])
  end

  def answer
    @answer ||= question.answers.find(params[:id])
  end
end

app/views/answers/_answer.html.slim
div id="answer-#{answer.id}" class="card mb-3"
  div class="card-header small text-muted"
    - if current_user
      div class="d-flex justify-content-center"
        = render 'answers/vote', answer: answer, user_vote: answer.votes.find_by(user: current_user)

    div class="answer-info text-center"
      => "Posted #{time_ago_in_words(answer.created_at)} ago by"
      span.text-info
        => answer.user.email

      - if answer == @best_answer
        span class="best-label badge bg-success rounded-pill"
          | Best answer

  .card-body
    .answer-body
      => answer.body

    hr

    - if answer.files.attached?
      div class="answer-files mt-3"
        label.small Files
        = render partial: 'answers/file', collection: answer.files, locals: { answer: }

    - if answer.links.any?
      div class="answer-links mt-3"
        label.small Links
        = render partial: 'answers/link', collection: answer.links, locals: { answer: }

    div class="mt-3 hidden" id="edit-answer-#{answer.id}"
      = render 'answers/edit_form', answer: answer

    div.comments
      = render answer.comments

    - if current_user
      = render 'comments/form', commentable: answer, comment: @answer_comment

  div class="card-footer small text-muted"
    - if policy(answer).update?
      => link_to 'Edit', '#', class: 'edit-answer-link btn btn-sm btn-warning', data: { answer_id: answer.id }

    - if policy(answer).destroy?
      => link_to 'Delete',
                 answer_path(answer),
                 method: :delete, data: { confirm: 'Are you sure?' }, remote: true,
                 class: 'btn btn-sm btn-danger answer-delete-link'

    - if policy(answer).best?
      = button_to 'Best',
                  best_answer_path(answer),
                  form: { class: 'd-inline-block' },
                  class: "best-answer-button btn btn-sm btn-success #{'hidden' if answer == @best_answer}",
                  remote: true

app/views/answers/_answer_simplified.html.slim
div id="answer-#{answer.id}" class="card mb-3"
  div class="card-header small text-muted"
    div class="answer-info text-center"
      => "Posted #{time_ago_in_words(answer.created_at)} ago by"
      span.text-info
        => answer.user.email

  .card-body
    .answer-body
      => answer.body

    hr

    - if answer.files.attached?
      div class="answer-files mt-3"
        label.small Files

        - answer.files.each do |file|
          div id="answer-file-#{file.id}" class="small"
            => link_to file.filename.to_s, url_for(file), class: 'text-decoration-none'

    - if answer.links.any?
      div class="answer-links mt-3"
        label.small Links

        - answer.links.each do |link|
          div id="answer-link-#{link.id}" class="small"
            => link_to link.title,
               link.url,
               class: "text-decoration-none #{'gist-link' if link.gist?}",
               data: { link_id: link.id }

    div.comments
      = render answer.comments

  div class="card-footer small text-muted"

app/views/answers/_edit_form.html.slim
= form_with(model: answer, local: false, data: { answer_id: answer.id }) do |f|
  .edit-answer-errors
    = render 'shared/errors', object: f.object

  .mb-3
    = f.text_area :body, class: 'form-control'

  .mb-3
    = f.file_field :files, multiple: true, direct_upload: true, class: 'form-control'

  .mb-3
    #answer-links
      = f.fields_for :links do |link_f|
        = render 'link_fields', f: link_f

      .links
        = link_to_add_association 'Add link', f, :links

  = f.submit 'Save', class: 'btn btn-sm btn-info'

app/views/answers/_file.html.slim
div id="answer-file-#{file.id}" class="small"
  => link_to file.filename.to_s, url_for(file), class: 'text-decoration-none'

  - if policy(answer).destroy_file?
    span class="badge bg-danger rounded-pill"
      = link_to '',
                destroy_file_answer_path(answer, file_id: file.id),
                method: :delete, remote: true,
                class: 'btn-close btn-close-white'

app/views/answers/_link.html.slim
div id="answer-link-#{link.id}" class="small"
  => link_to link.title,
             link.url,
             class: "text-decoration-none #{'gist-link' if link.gist?}",
             data: { link_id: link.id }

  - if policy(answer).destroy_link?
    span class="badge bg-danger rounded-pill"
      = link_to '',
              destroy_link_answer_path(answer, link_id: link.id),
              method: :delete, remote: true,
              class: 'btn-close btn-close-white'

  - if link.gist?
    div class="gist-content border border-light bg-light rounded-3 my-2 p-2 hidden"

app/views/answers/_link_fields.html.slim
div class="row nested-fields"
  div.col
    = f.text_field :title, placeholder: 'title', class: 'form-control form-control-sm'

  div.col
    = f.text_field :url, placeholder: 'url', class: 'form-control form-control-sm'

  = link_to_remove_association "Remove link", f

app/views/answers/_vote.html.slim
div class="vote-control d-flex align-items-center"
  = button_to vote_up_answer_path(answer),
              form: { data: { type: :json }, class: 'vote-up-form' },
              remote: true,
              class: "vote-up btn border-0 #{'hidden' if user_vote&.rate&.positive?}"
    = image_tag('vote-up.png')

  = button_to cancel_vote_answer_path(answer),
              form: { data: { type: :json },
                      class: "vote-up-cancel-form #{'hidden' unless user_vote&.rate&.positive?}" },
              method: :delete,
              remote: true,
              class: "vote-up-cancel btn border-0 #{'upvoted' if user_vote&.rate&.positive?}"
    = image_tag('vote-up.png')

  span class="fs-1 rating"
    = answer.rating

  = button_to vote_down_answer_path(answer),
              form: { data: { type: :json }, class: 'vote-down-form' },
              remote: true,
              class: "vote-down btn border-0 #{'hidden' if user_vote&.rate&.negative?}"
    = image_tag('vote-down.png')

  = button_to cancel_vote_answer_path(answer),
              form: { data: { type: :json },
                      class: "vote-down-cancel-form #{'hidden' unless user_vote&.rate&.negative?}" },
              method: :delete,
              remote: true,
              class: "vote-down-cancel btn border-0 #{'downvoted' if user_vote&.rate&.negative?}"
    = image_tag('vote-down.png')

app/views/answers/best.js.erb
<% if @question.best_answer == @answer %>
  answer = $('#answer-' + <%= @answer.id %>)
  answerBestButton = $('#answer-' + <%= @answer.id %> + ' .best-answer-button')

  $('.best-label').remove()
  $('<span class="best-label badge bg-success rounded-pill">Best answer</span>')
    .appendTo($('#answer-' + <%= @answer.id %> + ' .answer-info'))
  $('.best-answer-button').removeClass('hidden')
  answerBestButton.addClass('hidden')
  answer.prependTo('.answers')
<% end %>

app/views/answers/create.js.erb
$('.new-answer-errors').html('<%= render 'shared/errors', object: @answer %>')

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>')
  $('.new-answer').html('<%= j render 'questions/new_answer', answer: @new_answer %>')
<% end %>

app/views/answers/destroy.js.erb
$('#answer-' + <%= @answer.id %>).remove()

app/views/answers/destroy_file.js.erb
$('#answer-file-' + <%= @file.id %>).remove()

<% unless @answer.files.attached? %>
  $('#answer-' + <%= @answer.id %> + ' .answer-files').addClass('hidden')
<% end %>

app/views/answers/destroy_link.js.erb
$('#answer-link-' + <%= @link.id %>).remove()

<% if @answer.links.empty? %>
  $('#answer-' + <%= @answer.id %> + ' .answer-links').addClass('hidden')
<% end %>

$('#edit-answer-' + <%= @answer.id %>).html('<%= j render 'answers/edit_form', answer: @answer %>')

app/views/answers/update.js.erb
$('.edit-answer-errors').html('<%= render 'shared/errors', object: @answer %>')

<% if @answer.errors.empty? %>
  $('#answer-' + <%= @answer.id %>).replaceWith('<%= j render @answer %>')
<% end %>